live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#ff00ff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "#32302f"
blue = "#076678"
cyan = "#427b58"
green = "#79740e"
magenta = "#8f3f71"
red = "#9d0006"
white = "#928374"
yellow = "#b57614"

[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

[colors.primary]
background = "#1d2021"
bright_foreground = "#f9f5d7"
dim_foreground = "#f2e5bc"
foreground = "#ebdbb2"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Medium"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",?`|:\"' ()[]{}<>\t"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

#[url.launcher]
#program = "xdg-open"

[window]
decorations = "full"
dynamic_padding = true
startup_mode = "Maximized"
title = "Terminal"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 3
y = 3
